from __future__ import annotations

import json
import os
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd
from pydantic import BaseModel, ConfigDict, Field, ValidationError, field_validator


DEFAULT_LLM_MODEL = "openai/gpt-oss-20b"
DEFAULT_LLM_BASE_URL = "https://routerai.ru/api/v1"
DEFAULT_ROLLING_WINDOW = 252
DEFAULT_TRADING_DAYS = 252
LAST_LLM_DEBUG: dict[str, Any] = {}


SYSTEM_PROMPT = """You are a careful walk-forward portfolio optimizer.
Use only the supplied training-window evidence and previous scored portfolios. Propose practical long-only portfolio variants that balance return, risk, and concentration.
Return only valid JSON with a top-level "candidates" array. Do not include prose, markdown, code fences, comments, explanations, or trailing commas."""


SYSTEM_PROMPT_RU = """Ты аккуратный walk-forward оптимизатор портфеля.
Используй только переданные данные обучающего окна и уже оцененные портфели. Предлагай практичные long-only варианты портфелей с балансом доходности, риска и концентрации.
Верни только валидный JSON с верхнеуровневым массивом "candidates". Без текста, markdown, code fence, комментариев, объяснений и trailing comma."""


@dataclass(frozen=True)
class WeightedPortfolioEvaluation:
    weights: dict[str, float]
    score: float
    metrics: dict[str, float]


@dataclass(frozen=True)
class RollingReturnRiskContext:
    tickers: list[str]
    logret_mat: np.ndarray
    cov_tensor: np.ndarray
    window: int
    trading_days: int


class PortfolioCandidate(BaseModel):
    model_config = ConfigDict(extra="ignore")

    weights: dict[str, float] = Field(
        description="Portfolio weights by ticker. Keys are tickers from available_assets, values are positive numbers from 0 to 1."
    )

    @field_validator("weights", mode="before")
    @classmethod
    def parse_weights(cls, value: Any) -> dict[str, float]:
        if not isinstance(value, dict):
            raise ValueError("weights must be an object/dict")
        parsed: dict[str, float] = {}
        for asset, weight in value.items():
            try:
                if isinstance(weight, str):
                    cleaned = weight.strip().replace("%", "")
                    parsed_weight = float(cleaned)
                    if parsed_weight > 1:
                        parsed_weight = parsed_weight / 100.0
                else:
                    parsed_weight = float(weight)
            except (TypeError, ValueError):
                continue
            if parsed_weight > 0:
                parsed[str(asset)] = parsed_weight
        if not parsed:
            raise ValueError("weights must contain at least one positive numeric value")
        return parsed


class PortfolioCandidateBatch(BaseModel):
    model_config = ConfigDict(extra="ignore")

    candidates: list[PortfolioCandidate] = Field(
        description="Candidate portfolios generated by the LLM. Each candidate must contain a weights object."
    )


def build_rolling_return_risk_context(
    prices: pd.DataFrame,
    window: int = DEFAULT_ROLLING_WINDOW,
    trading_days: int = DEFAULT_TRADING_DAYS,
) -> RollingReturnRiskContext:
    numeric_prices = prices.astype(float).replace([np.inf, -np.inf, 0], np.nan).ffill().bfill()
    numeric_prices = numeric_prices.dropna(axis=1, how="any")
    logret_df = np.log(numeric_prices / numeric_prices.shift(1))
    logret_df = logret_df.replace([np.inf, -np.inf], np.nan).dropna(how="any")
    if len(logret_df) < window:
        raise ValueError(f"Not enough return rows for rolling window={window}: got {len(logret_df)}")

    tickers = list(logret_df.columns)
    rolling_cov = logret_df.rolling(window).cov()
    eval_dates = logret_df.index[window - 1 :]
    cov_tensor = np.empty((len(eval_dates), len(tickers), len(tickers)), dtype=np.float64)
    for ti, date in enumerate(eval_dates):
        block = rolling_cov.loc[date].loc[tickers, tickers].values.astype(np.float64)
        cov_tensor[ti] = np.nan_to_num(block, nan=0.0, posinf=0.0, neginf=0.0)

    return RollingReturnRiskContext(
        tickers=tickers,
        logret_mat=np.ascontiguousarray(logret_df.values.astype(np.float64)),
        cov_tensor=cov_tensor,
        window=window,
        trading_days=trading_days,
    )


def rolling_metrics_from_weights(
    weights: dict[str, float] | pd.Series,
    context: RollingReturnRiskContext,
    normalize: bool = True,
    allow_short: bool = False,
) -> dict:
    w = pd.Series(weights, dtype=float)

    if not allow_short and (w < 0).any():
        bad = w[w < 0]
        raise ValueError(f"Negative weights are not allowed: {bad.to_dict()}")

    missing = [ticker for ticker in w.index if ticker not in context.tickers]
    if missing:
        raise KeyError(f"Tickers not found in rolling context: {missing}")

    if normalize:
        total = float(w.sum())
        if total == 0:
            raise ValueError("Sum of weights is 0.")
        w = w / total

    full_w = np.zeros(len(context.tickers), dtype=np.float64)
    ticker_pos = {ticker: i for i, ticker in enumerate(context.tickers)}
    for ticker, weight in w.items():
        full_w[ticker_pos[ticker]] = float(weight)

    portfolio_ret_daily = context.logret_mat @ full_w
    mu_ann = float(np.nanmean(portfolio_ret_daily) * context.trading_days)
    var_t = np.einsum("i,tij,j->t", full_w, context.cov_tensor, full_w) * context.trading_days
    rolling_var = pd.Series(np.clip(var_t, 0.0, None), name="rolling_var_ann")
    rolling_sigma = np.sqrt(rolling_var)

    return {
        "weights": w,
        "mu_ann": mu_ann,
        "mean_var_ann": float(rolling_var.mean()),
        "median_var_ann": float(rolling_var.median()),
        "mean_sigma_ann": float(rolling_sigma.mean()),
        "median_sigma_ann": float(rolling_sigma.median()),
        "sigma_q_0.8": float(rolling_sigma.quantile(0.8)),
        "sigma_q_0.9": float(rolling_sigma.quantile(0.9)),
        "sigma_q_0.95": float(rolling_sigma.quantile(0.95)),
    }


def portfolio_metrics_rolling(
    weights: dict[str, float] | pd.Series,
    prices: pd.DataFrame,
    window: int = DEFAULT_ROLLING_WINDOW,
    trading_days: int = DEFAULT_TRADING_DAYS,
    normalize: bool = True,
    allow_short: bool = False,
) -> dict:
    context = build_rolling_return_risk_context(prices, window=window, trading_days=trading_days)
    return rolling_metrics_from_weights(weights, context, normalize=normalize, allow_short=allow_short)


def latest_asset_prices(prices: pd.DataFrame) -> pd.Series:
    numeric_prices = prices.astype(float).replace([np.inf, -np.inf, 0], np.nan).ffill()
    latest = numeric_prices.apply(lambda col: col.dropna().iloc[-1] if col.notna().any() else np.nan)
    return latest.dropna()


def share_allocation(
    weights: dict[str, float] | pd.Series,
    latest_prices: pd.Series,
    capital: float,
) -> tuple[pd.DataFrame, dict[str, float]]:
    w = pd.Series(weights, dtype=float)
    w = w[w > 0]
    total_weight = float(w.sum())
    if total_weight <= 0:
        raise ValueError("Sum of positive weights is 0.")
    if capital <= 0:
        raise ValueError("Capital must be positive.")

    w = w / total_weight
    missing = [ticker for ticker in w.index if ticker not in latest_prices.index]
    if missing:
        raise KeyError(f"Tickers not found in latest prices: {missing}")

    rows = []
    invested_value = 0.0
    for asset, weight in w.sort_values(ascending=False).items():
        price = float(latest_prices.loc[asset])
        target_value = float(capital * weight)
        quantity = int(np.floor(target_value / price)) if price > 0 else 0
        value = float(quantity * price)
        invested_value += value
        rows.append(
            {
                "asset": asset,
                "weight": float(weight),
                "price": price,
                "target_value": target_value,
                "quantity": quantity,
                "invested_value": value,
            }
        )

    allocation = pd.DataFrame(rows)
    allocation["actual_weight"] = allocation["invested_value"] / invested_value if invested_value > 0 else 0.0
    summary = {
        "capital": float(capital),
        "invested_value": float(invested_value),
        "cash_left": float(capital - invested_value),
        "capital_utilization": float(invested_value / capital),
    }
    return allocation, summary


def evaluate_weighted_portfolio(
    weights: dict[str, float],
    context: RollingReturnRiskContext,
    max_sigma_ann: float,
    min_assets: int,
    max_assets: int,
) -> WeightedPortfolioEvaluation:
    clean = {asset: float(weight) for asset, weight in weights.items() if asset in context.tickers and float(weight) > 0}
    if not (min_assets <= len(clean) <= max_assets):
        return WeightedPortfolioEvaluation(weights=clean, score=-999.0, metrics={"n_assets": len(clean), "valid": 0})

    try:
        metrics = rolling_metrics_from_weights(clean, context, normalize=True, allow_short=False)
    except (ValueError, KeyError):
        return WeightedPortfolioEvaluation(weights=clean, score=-999.0, metrics={"n_assets": len(clean), "valid": 0})

    normalized_weights = metrics["weights"].to_dict()
    sigma = float(metrics["sigma_q_0.9"])
    mu = float(metrics["mu_ann"])
    risk_violation = max(0.0, sigma - max_sigma_ann)
    concentration = float(sum(weight * weight for weight in normalized_weights.values()))
    n_assets = len(normalized_weights)
    score = mu - 20.0 * risk_violation - 0.02 * concentration

    out_metrics = {
        "valid": 1,
        "mu_ann": mu,
        "sigma_ann": sigma,
        "sigma_q_0.8": float(metrics["sigma_q_0.8"]),
        "sigma_q_0.9": sigma,
        "sigma_q_0.95": float(metrics["sigma_q_0.95"]),
        "mean_sigma_ann": float(metrics["mean_sigma_ann"]),
        "median_sigma_ann": float(metrics["median_sigma_ann"]),
        "mean_var_ann": float(metrics["mean_var_ann"]),
        "median_var_ann": float(metrics["median_var_ann"]),
        "risk_violation": risk_violation,
        "concentration": concentration,
        "n_assets": n_assets,
    }
    return WeightedPortfolioEvaluation(weights=normalized_weights, score=float(score), metrics=out_metrics)


def random_weighted_portfolio(
    rng: np.random.Generator,
    assets: list[str],
    min_assets: int,
    max_assets: int,
) -> dict[str, float]:
    size = int(rng.integers(min_assets, min(max_assets, len(assets)) + 1))
    chosen = [str(asset) for asset in rng.choice(assets, size=size, replace=False)]
    raw = rng.dirichlet(np.ones(size))
    return dict(zip(chosen, raw))


def optimize_random_return_under_risk(
    prices: pd.DataFrame,
    n_portfolios: int = 5000,
    min_assets: int = 3,
    max_assets: int = 10,
    max_sigma_ann: float = 0.35,
    rolling_window: int = DEFAULT_ROLLING_WINDOW,
    trading_days: int = DEFAULT_TRADING_DAYS,
    seed: int = 42,
    collect_history: bool = True,
) -> tuple[WeightedPortfolioEvaluation, pd.DataFrame]:
    rng = np.random.default_rng(seed)
    numeric_prices = prices.astype(float).replace([np.inf, -np.inf, 0], np.nan).ffill().bfill()
    numeric_prices = numeric_prices.dropna(axis=1, how="any")
    logret_df = np.log(numeric_prices / numeric_prices.shift(1)).replace([np.inf, -np.inf], np.nan).dropna(how="any")
    if len(logret_df) < rolling_window:
        raise ValueError(f"Not enough return rows for rolling window={rolling_window}: got {len(logret_df)}")

    tickers = list(logret_df.columns)
    if len(tickers) < min_assets:
        raise ValueError(f"Not enough assets for min_assets={min_assets}: got {len(tickers)}")

    max_size = min(max_assets, len(tickers))
    weight_matrix = np.zeros((n_portfolios, len(tickers)), dtype=np.float64)
    n_assets = np.empty(n_portfolios, dtype=np.int64)
    for portfolio_id in range(n_portfolios):
        size = int(rng.integers(min_assets, max_size + 1))
        positions = rng.choice(len(tickers), size=size, replace=False)
        raw = rng.dirichlet(np.ones(size))
        weight_matrix[portfolio_id, positions] = raw
        n_assets[portfolio_id] = size

    portfolio_returns = logret_df.values @ weight_matrix.T
    mu_ann = np.nanmean(portfolio_returns, axis=0) * trading_days
    rolling_sigma = pd.DataFrame(portfolio_returns).rolling(rolling_window).std(ddof=1) * np.sqrt(trading_days)
    sigma_q_08 = rolling_sigma.quantile(0.8).to_numpy()
    sigma_q_09 = rolling_sigma.quantile(0.9).to_numpy()
    sigma_q_095 = rolling_sigma.quantile(0.95).to_numpy()
    mean_sigma_ann = rolling_sigma.mean().to_numpy()
    median_sigma_ann = rolling_sigma.median().to_numpy()
    rolling_var = rolling_sigma.pow(2)
    mean_var_ann = rolling_var.mean().to_numpy()
    median_var_ann = rolling_var.median().to_numpy()

    risk_violation = np.maximum(0.0, sigma_q_09 - max_sigma_ann)
    concentration = np.sum(weight_matrix * weight_matrix, axis=1)
    score = mu_ann - 20.0 * risk_violation - 0.02 * concentration
    score = np.nan_to_num(score, nan=-999.0, posinf=-999.0, neginf=-999.0)
    best_idx = int(np.argmax(score))

    def weights_for(index: int) -> dict[str, float]:
        row = weight_matrix[index]
        return {ticker: float(row[pos]) for pos, ticker in enumerate(tickers) if row[pos] > 0}

    best_metrics = {
        "valid": 1,
        "mu_ann": float(mu_ann[best_idx]),
        "sigma_ann": float(sigma_q_09[best_idx]),
        "sigma_q_0.8": float(sigma_q_08[best_idx]),
        "sigma_q_0.9": float(sigma_q_09[best_idx]),
        "sigma_q_0.95": float(sigma_q_095[best_idx]),
        "mean_sigma_ann": float(mean_sigma_ann[best_idx]),
        "median_sigma_ann": float(median_sigma_ann[best_idx]),
        "mean_var_ann": float(mean_var_ann[best_idx]),
        "median_var_ann": float(median_var_ann[best_idx]),
        "risk_violation": float(risk_violation[best_idx]),
        "concentration": float(concentration[best_idx]),
        "n_assets": int(n_assets[best_idx]),
    }
    best = WeightedPortfolioEvaluation(
        weights=weights_for(best_idx),
        score=float(score[best_idx]),
        metrics=best_metrics,
    )

    if not collect_history:
        return best, pd.DataFrame()

    rows = []
    for portfolio_id in range(n_portfolios):
        row = {
            "portfolio_id": portfolio_id,
            "score": float(score[portfolio_id]),
            "weights": json.dumps(weights_for(portfolio_id), ensure_ascii=False),
            "valid": 1,
            "mu_ann": float(mu_ann[portfolio_id]),
            "sigma_ann": float(sigma_q_09[portfolio_id]),
            "sigma_q_0.8": float(sigma_q_08[portfolio_id]),
            "sigma_q_0.9": float(sigma_q_09[portfolio_id]),
            "sigma_q_0.95": float(sigma_q_095[portfolio_id]),
            "mean_sigma_ann": float(mean_sigma_ann[portfolio_id]),
            "median_sigma_ann": float(median_sigma_ann[portfolio_id]),
            "mean_var_ann": float(mean_var_ann[portfolio_id]),
            "median_var_ann": float(median_var_ann[portfolio_id]),
            "risk_violation": float(risk_violation[portfolio_id]),
            "concentration": float(concentration[portfolio_id]),
            "n_assets": int(n_assets[portfolio_id]),
        }
        rows.append(row)
    return best, pd.DataFrame(rows)


def realized_portfolio_metrics(
    prices: pd.DataFrame,
    weights: dict[str, float],
    trading_days: int = DEFAULT_TRADING_DAYS,
) -> dict[str, Any]:
    w = pd.Series(weights, dtype=float)
    total = float(w.sum())
    if total <= 0:
        raise ValueError("Sum of weights is 0.")
    w = w / total

    missing = [ticker for ticker in w.index if ticker not in prices.columns]
    if missing:
        raise KeyError(f"Tickers not found in realized prices: {missing}")

    price_block = prices.loc[:, list(w.index)].astype(float).replace([np.inf, -np.inf, 0], np.nan).ffill().bfill()
    log_returns = np.log(price_block / price_block.shift(1)).replace([np.inf, -np.inf], np.nan).dropna(how="any")
    if log_returns.empty:
        return {
            "realized_return": 0.0,
            "realized_vol": 0.0,
            "realized_mu_ann": 0.0,
            "daily_returns": pd.Series(dtype=float),
        }

    portfolio_log_returns = log_returns @ w
    realized_return = float(np.exp(portfolio_log_returns.sum()) - 1.0)
    realized_vol = float(portfolio_log_returns.std(ddof=1) * np.sqrt(trading_days)) if len(portfolio_log_returns) > 1 else 0.0
    realized_mu_ann = float(portfolio_log_returns.mean() * trading_days)
    return {
        "realized_return": realized_return,
        "realized_vol": realized_vol,
        "realized_mu_ann": realized_mu_ann,
        "daily_returns": portfolio_log_returns,
    }


def max_drawdown_from_equity(equity: pd.Series) -> float:
    if equity.empty:
        return 0.0
    running_max = equity.cummax()
    drawdown = equity / running_max - 1.0
    return float(drawdown.min())


def summarize_walk_forward(
    results: pd.DataFrame,
    daily_return_parts: list[pd.Series],
    train_window: int,
    test_window: int,
    step: int,
    trading_days: int,
    extra_summary: dict[str, Any] | None = None,
) -> tuple[pd.DataFrame, dict[str, Any]]:
    if daily_return_parts:
        all_daily_returns = pd.concat(daily_return_parts).sort_index()
        all_daily_returns = all_daily_returns[~all_daily_returns.index.duplicated(keep="last")]
    else:
        all_daily_returns = pd.Series(dtype=float, name="daily_log_return")
    all_daily_returns.name = "daily_log_return"

    equity = np.exp(all_daily_returns.cumsum()) if not all_daily_returns.empty else pd.Series(dtype=float)
    equity_curve = pd.DataFrame(
        {
            "date": equity.index.astype(str),
            "daily_log_return": all_daily_returns.values,
            "equity": equity.values,
            "drawdown": (equity / equity.cummax() - 1.0).values if not equity.empty else [],
        }
    )

    cumulative_return = float(equity.iloc[-1] - 1.0) if not equity.empty else 0.0
    n_days = int(len(all_daily_returns))
    annualized_return = float(equity.iloc[-1] ** (trading_days / n_days) - 1.0) if n_days > 0 and not equity.empty else 0.0
    annualized_volatility = float(all_daily_returns.std(ddof=1) * np.sqrt(trading_days)) if n_days > 1 else 0.0
    sharpe_like = float(annualized_return / annualized_volatility) if annualized_volatility > 0 else 0.0
    summary: dict[str, Any] = {
        "steps": int(len(results)),
        "train_window": int(train_window),
        "test_window": int(test_window),
        "step": int(step),
        "cumulative_return": cumulative_return,
        "annualized_return": annualized_return,
        "annualized_volatility": annualized_volatility,
        "sharpe_like": sharpe_like,
        "max_drawdown": max_drawdown_from_equity(equity),
        "win_rate": float((results["realized_return_test"] > 0).mean()) if not results.empty else 0.0,
        "avg_n_assets": float(results["n_assets"].mean()) if not results.empty else 0.0,
    }
    if extra_summary:
        summary.update(extra_summary)
    return equity_curve, summary


def run_walk_forward_baseline(
    prices: pd.DataFrame,
    train_window: int = 504,
    test_window: int = 21,
    step: int = 21,
    random_portfolios: int = 5000,
    min_assets: int = 3,
    max_assets: int = 10,
    max_sigma_ann: float = 0.35,
    rolling_window: int = 21,
    trading_days: int = DEFAULT_TRADING_DAYS,
    seed: int = 42,
    verbose: bool = True,
    start_step: int = 0,
    max_steps: int | None = None,
) -> tuple[pd.DataFrame, pd.DataFrame, dict[str, float]]:
    numeric_prices = prices.astype(float).replace([np.inf, -np.inf, 0], np.nan).ffill().bfill()
    numeric_prices = numeric_prices.dropna(axis=1, how="any")
    if len(numeric_prices) < train_window + test_window:
        raise ValueError(
            f"Not enough rows for walk-forward: got {len(numeric_prices)}, "
            f"need at least {train_window + test_window}"
        )

    rows: list[dict[str, Any]] = []
    daily_return_parts: list[pd.Series] = []
    train_starts = list(range(0, len(numeric_prices) - train_window - test_window + 1, step))
    if start_step < 0:
        start_step = max(0, len(train_starts) + start_step)
    selected_starts = train_starts[start_step:]
    if max_steps is not None:
        selected_starts = selected_starts[:max_steps]

    for local_step_id, train_start in enumerate(selected_starts):
        step_id = start_step + local_step_id
        train_end = train_start + train_window
        test_end = train_end + test_window
        train_prices = numeric_prices.iloc[train_start:train_end]
        test_prices = numeric_prices.iloc[train_end - 1 : test_end]

        best, _ = optimize_random_return_under_risk(
            train_prices,
            n_portfolios=random_portfolios,
            min_assets=min_assets,
            max_assets=max_assets,
            max_sigma_ann=max_sigma_ann,
            rolling_window=rolling_window,
            trading_days=trading_days,
            seed=seed + step_id,
            collect_history=False,
        )
        realized = realized_portfolio_metrics(test_prices, best.weights, trading_days=trading_days)
        daily_returns = realized["daily_returns"]
        if isinstance(daily_returns, pd.Series) and not daily_returns.empty:
            daily_return_parts.append(daily_returns)

        row = {
            "step": step_id,
            "train_start": str(train_prices.index[0]),
            "train_end": str(train_prices.index[-1]),
            "test_start": str(numeric_prices.index[train_end]),
            "test_end": str(numeric_prices.index[test_end - 1]),
            "score_train": best.score,
            "mu_ann_train": best.metrics.get("mu_ann", np.nan),
            "sigma_q_0.9_train": best.metrics.get("sigma_q_0.9", np.nan),
            "risk_violation_train": best.metrics.get("risk_violation", np.nan),
            "realized_return_test": realized["realized_return"],
            "realized_vol_test": realized["realized_vol"],
            "realized_mu_ann_test": realized["realized_mu_ann"],
            "n_assets": int(best.metrics.get("n_assets", len(best.weights))),
            "weights_json": json.dumps(best.weights, ensure_ascii=False),
        }
        rows.append(row)
        if verbose:
            print(
                f"step={step_id:>2} train={row['train_start']}..{row['train_end']} "
                f"test={row['test_start']}..{row['test_end']} "
                f"score={best.score:.4f} test_return={realized['realized_return']:.4f} "
                f"assets={row['n_assets']} weights={format_weights_compact(best.weights)}",
                flush=True,
            )
        step_id += 1

    results = pd.DataFrame(rows)
    equity_curve, summary = summarize_walk_forward(
        results,
        daily_return_parts,
        train_window,
        test_window,
        step,
        trading_days,
        extra_summary={"random_portfolios": int(random_portfolios), "optimizer": "random_baseline"},
    )
    summary["start_step"] = int(start_step)
    summary["max_steps"] = max_steps
    return results, equity_curve, summary


def run_walk_forward_llm_optimizer(
    prices: pd.DataFrame,
    model: str,
    train_window: int = 504,
    test_window: int = 21,
    step: int = 21,
    min_assets: int = 3,
    max_assets: int = 10,
    max_sigma_ann: float = 0.35,
    rolling_window: int = 21,
    trading_days: int = DEFAULT_TRADING_DAYS,
    initial_random_samples: int = 10,
    iterations: int = 5,
    candidates_per_iter: int = 5,
    llm_attempts_per_iteration: int = 2,
    seed: int = 42,
    base_url: str | None = None,
    temperature: float = 1.0,
    prompt_dir: str | Path | None = None,
    verbose: bool = True,
    optimizer_verbose: bool = False,
    history_dir: str | Path | None = None,
    start_step: int = 0,
    max_steps: int | None = None,
) -> tuple[pd.DataFrame, pd.DataFrame, dict[str, Any]]:
    numeric_prices = prices.astype(float).replace([np.inf, -np.inf, 0], np.nan).ffill().bfill()
    numeric_prices = numeric_prices.dropna(axis=1, how="any")
    if len(numeric_prices) < train_window + test_window:
        raise ValueError(
            f"Not enough rows for walk-forward: got {len(numeric_prices)}, "
            f"need at least {train_window + test_window}"
        )

    rows: list[dict[str, Any]] = []
    daily_return_parts: list[pd.Series] = []
    prompt_base = Path(prompt_dir) if prompt_dir else None
    if prompt_base:
        prompt_base.mkdir(parents=True, exist_ok=True)
    history_base = Path(history_dir) if history_dir else None
    if history_base:
        history_base.mkdir(parents=True, exist_ok=True)

    train_starts = list(range(0, len(numeric_prices) - train_window - test_window + 1, step))
    if start_step < 0:
        start_step = max(0, len(train_starts) + start_step)
    selected_starts = train_starts[start_step:]
    if max_steps is not None:
        selected_starts = selected_starts[:max_steps]

    for local_step_id, train_start in enumerate(selected_starts):
        step_id = start_step + local_step_id
        train_end = train_start + train_window
        test_end = train_end + test_window
        train_prices = numeric_prices.iloc[train_start:train_end]
        test_prices = numeric_prices.iloc[train_end - 1 : test_end]
        prompt_out = prompt_base / f"step_{step_id:03d}_last_llm_prompt.json" if prompt_base else None

        if verbose:
            print(
                f"step={step_id:>2} model={model} "
                f"train={train_prices.index[0]}..{train_prices.index[-1]} "
                f"test={numeric_prices.index[train_end]}..{numeric_prices.index[test_end - 1]}",
                flush=True,
            )

        best, history = optimize_return_under_risk(
            prices=train_prices,
            min_assets=min_assets,
            max_assets=max_assets,
            max_sigma_ann=max_sigma_ann,
            rolling_window=rolling_window,
            trading_days=trading_days,
            initial_random_samples=initial_random_samples,
            iterations=iterations,
            candidates_per_iter=candidates_per_iter,
            llm_attempts_per_iteration=llm_attempts_per_iteration,
            seed=seed + step_id,
            model=model,
            base_url=base_url,
            temperature=temperature,
            prompt_out=prompt_out,
            verbose=optimizer_verbose,
            progress=False,
        )
        if history_base:
            history_out = history.copy()
            history_out["step"] = step_id
            history_out["model"] = model
            history_out["train_start"] = str(train_prices.index[0])
            history_out["train_end"] = str(train_prices.index[-1])
            history_out["test_start"] = str(numeric_prices.index[train_end])
            history_out["test_end"] = str(numeric_prices.index[test_end - 1])
            history_out.to_csv(history_base / f"step_{step_id:03d}_history.csv", index=False)
            epoch_log = history.attrs.get("epoch_log")
            if isinstance(epoch_log, pd.DataFrame):
                epoch_log_out = epoch_log.copy()
                epoch_log_out["step"] = step_id
                epoch_log_out["model"] = model
                epoch_log_out["train_start"] = str(train_prices.index[0])
                epoch_log_out["train_end"] = str(train_prices.index[-1])
                epoch_log_out["test_start"] = str(numeric_prices.index[train_end])
                epoch_log_out["test_end"] = str(numeric_prices.index[test_end - 1])
                epoch_log_out.to_csv(history_base / f"step_{step_id:03d}_epoch_log.csv", index=False)
        realized = realized_portfolio_metrics(test_prices, best.weights, trading_days=trading_days)
        daily_returns = realized["daily_returns"]
        if isinstance(daily_returns, pd.Series) and not daily_returns.empty:
            daily_return_parts.append(daily_returns)

        row = {
            "step": step_id,
            "model": model,
            "train_start": str(train_prices.index[0]),
            "train_end": str(train_prices.index[-1]),
            "test_start": str(numeric_prices.index[train_end]),
            "test_end": str(numeric_prices.index[test_end - 1]),
            "score_train": best.score,
            "mu_ann_train": best.metrics.get("mu_ann", np.nan),
            "sigma_q_0.9_train": best.metrics.get("sigma_q_0.9", np.nan),
            "risk_violation_train": best.metrics.get("risk_violation", np.nan),
            "realized_return_test": realized["realized_return"],
            "realized_vol_test": realized["realized_vol"],
            "realized_mu_ann_test": realized["realized_mu_ann"],
            "n_assets": int(best.metrics.get("n_assets", len(best.weights))),
            "evaluated_portfolios_train": int(len(history)),
            "weights_json": json.dumps(best.weights, ensure_ascii=False),
        }
        rows.append(row)
        if verbose:
            print(
                f"step={step_id:>2} score={best.score:.4f} "
                f"test_return={realized['realized_return']:.4f} "
                f"assets={row['n_assets']} weights={format_weights_compact(best.weights)}",
                flush=True,
            )
        step_id += 1

    results = pd.DataFrame(rows)
    equity_curve, summary = summarize_walk_forward(
        results,
        daily_return_parts,
        train_window,
        test_window,
        step,
        trading_days,
        extra_summary={
            "optimizer": "llm",
            "model": model,
            "initial_random_samples": int(initial_random_samples),
            "iterations": int(iterations),
            "candidates_per_iter": int(candidates_per_iter),
            "llm_attempts_per_iteration": int(llm_attempts_per_iteration),
            "optimizer_verbose": bool(optimizer_verbose),
            "start_step": int(start_step),
            "max_steps": max_steps,
        },
    )
    return results, equity_curve, summary


def safe_model_dir_name(model_name: str) -> str:
    """Return a filesystem-safe directory name for a model id."""
    return "".join(ch if ch.isalnum() or ch in "-_." else "_" for ch in model_name)


def load_model_epoch_scores(model_out_dir: str | Path, model_name: str) -> pd.DataFrame:
    """Load per-step histories and aggregate train scores by LLM iteration."""
    history_dir = Path(model_out_dir) / "histories"
    history_frames: list[pd.DataFrame] = []
    epoch_log_frames: list[pd.DataFrame] = []

    for history_path in sorted(history_dir.glob("step_*_history.csv")):
        history_df = pd.read_csv(history_path)
        if "score" not in history_df.columns or "iteration" not in history_df.columns:
            continue
        if "step" not in history_df.columns:
            history_df["step"] = int(history_path.stem.split("_")[1])
        history_df["model"] = model_name
        history_frames.append(history_df)

    for epoch_path in sorted(history_dir.glob("step_*_epoch_log.csv")):
        epoch_df = pd.read_csv(epoch_path)
        if "iteration" not in epoch_df.columns:
            continue
        if "step" not in epoch_df.columns:
            epoch_df["step"] = int(epoch_path.stem.split("_")[1])
        epoch_df["model"] = model_name
        epoch_log_frames.append(epoch_df)

    if history_frames:
        history_all = pd.concat(history_frames, ignore_index=True)
        mean_scores = (
            history_all.groupby(["model", "step", "iteration"], as_index=False)
            .agg(
                mean_score=("score", "mean"),
                max_score=("score", "max"),
                portfolios_count=("score", "size"),
            )
        )
    else:
        mean_scores = pd.DataFrame(
            columns=["model", "step", "iteration", "mean_score", "max_score", "portfolios_count"]
        )

    if epoch_log_frames:
        epoch_logs = pd.concat(epoch_log_frames, ignore_index=True)
        best_source_col = "best_score_after" if "best_score_after" in epoch_logs.columns else "best_score"
        agg_kwargs: dict[str, tuple[str, str]] = {"best_score": (best_source_col, "max")}
        if "parsed_candidates" in epoch_logs.columns:
            agg_kwargs["parsed_candidates"] = ("parsed_candidates", "sum")
        if "accepted_candidates" in epoch_logs.columns:
            agg_kwargs["accepted_candidates"] = ("accepted_candidates", "sum")
        epoch_scores = epoch_logs.groupby(["model", "step", "iteration"], as_index=False).agg(**agg_kwargs)
    else:
        epoch_scores = pd.DataFrame(
            columns=["model", "step", "iteration", "best_score", "parsed_candidates", "accepted_candidates"]
        )

    merged = epoch_scores.merge(mean_scores, on=["model", "step", "iteration"], how="outer")
    if merged.empty:
        return merged
    merged = merged.sort_values(["model", "step", "iteration"]).reset_index(drop=True)
    merged["epoch"] = merged["iteration"]
    return merged


def enrich_walk_forward_equity_curve(equity_curve: pd.DataFrame, results: pd.DataFrame) -> pd.DataFrame:
    """Attach step-level train/test metadata to each daily equity row."""
    enriched = equity_curve.copy()
    for column in ["step", "score_train", "realized_return_test", "n_assets"]:
        if column not in enriched.columns:
            enriched[column] = np.nan

    equity_dates = pd.to_datetime(enriched["date"])
    for _, result_row in results.iterrows():
        date_mask = (
            (equity_dates >= pd.to_datetime(result_row["test_start"]))
            & (equity_dates <= pd.to_datetime(result_row["test_end"]))
        )
        enriched.loc[date_mask, "step"] = int(result_row["step"])
        enriched.loc[date_mask, "score_train"] = float(result_row["score_train"])
        enriched.loc[date_mask, "realized_return_test"] = float(result_row["realized_return_test"])
        enriched.loc[date_mask, "n_assets"] = int(result_row["n_assets"])

    return enriched


def run_multi_model_walk_forward_llm(
    prices: pd.DataFrame,
    models: list[str],
    out_dir: str | Path,
    train_window: int = 504,
    test_window: int = 21,
    step: int = 21,
    min_assets: int = 3,
    max_assets: int = 10,
    max_sigma_ann: float = 0.35,
    rolling_window: int = 21,
    trading_days: int = DEFAULT_TRADING_DAYS,
    initial_random_samples: int = 10,
    iterations: int = 20,
    candidates_per_iter: int = 3,
    llm_attempts_per_iteration: int = 1,
    seed: int = 42,
    base_url: str | None = None,
    temperature: float = 1.0,
    verbose: bool = True,
    optimizer_verbose: bool = True,
    start_step: int = -1,
    max_steps: int | None = 1,
) -> tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame, pd.DataFrame]:
    """Run walk-forward LLM optimization for multiple models and save tidy outputs."""
    out_path = Path(out_dir)
    out_path.mkdir(parents=True, exist_ok=True)

    all_results: list[pd.DataFrame] = []
    all_equity_curves: list[pd.DataFrame] = []
    all_summaries: list[dict[str, Any]] = []
    all_epoch_scores: list[pd.DataFrame] = []

    for model_name in models:
        if verbose:
            print("=" * 80)
            print("MODEL:", model_name)

        model_out_dir = out_path / safe_model_dir_name(model_name)
        model_out_dir.mkdir(parents=True, exist_ok=True)

        results, equity_curve, summary = run_walk_forward_llm_optimizer(
            prices=prices,
            model=model_name,
            train_window=train_window,
            test_window=test_window,
            step=step,
            min_assets=min_assets,
            max_assets=max_assets,
            max_sigma_ann=max_sigma_ann,
            rolling_window=rolling_window,
            trading_days=trading_days,
            initial_random_samples=initial_random_samples,
            iterations=iterations,
            candidates_per_iter=candidates_per_iter,
            llm_attempts_per_iteration=llm_attempts_per_iteration,
            seed=seed,
            base_url=base_url,
            temperature=temperature,
            prompt_dir=model_out_dir / "prompts",
            history_dir=model_out_dir / "histories",
            verbose=verbose,
            optimizer_verbose=optimizer_verbose,
            start_step=start_step,
            max_steps=max_steps,
        )

        results["model"] = model_name
        equity_curve["model"] = model_name
        equity_curve = enrich_walk_forward_equity_curve(equity_curve, results)

        epoch_scores = load_model_epoch_scores(model_out_dir, model_name)
        if not epoch_scores.empty:
            epoch_scores.to_csv(model_out_dir / "walk_forward_epoch_scores.csv", index=False)
            all_epoch_scores.append(epoch_scores)

        summary["model"] = model_name
        summary["model_dir"] = str(model_out_dir)

        results.to_csv(model_out_dir / "walk_forward_results.csv", index=False)
        equity_curve.to_csv(model_out_dir / "walk_forward_equity_curve.csv", index=False)
        (model_out_dir / "walk_forward_summary.json").write_text(
            json.dumps(summary, indent=2, ensure_ascii=False),
            encoding="utf-8",
        )

        all_results.append(results)
        all_equity_curves.append(equity_curve)
        all_summaries.append(summary)

    results_all = pd.concat(all_results, ignore_index=True) if all_results else pd.DataFrame()
    equity_curve_all = pd.concat(all_equity_curves, ignore_index=True) if all_equity_curves else pd.DataFrame()
    summary_all = pd.DataFrame(all_summaries)
    epoch_scores_all = pd.concat(all_epoch_scores, ignore_index=True) if all_epoch_scores else pd.DataFrame()

    results_all.to_csv(out_path / "all_models_walk_forward_results.csv", index=False)
    equity_curve_all.to_csv(out_path / "all_models_walk_forward_equity_curve.csv", index=False)
    summary_all.to_csv(out_path / "all_models_walk_forward_summary.csv", index=False)
    epoch_scores_all.to_csv(out_path / "all_models_walk_forward_epoch_scores.csv", index=False)

    return results_all, equity_curve_all, summary_all, epoch_scores_all


def plot_walk_forward_comparison(
    results_all: pd.DataFrame,
    equity_curve_all: pd.DataFrame,
    epoch_scores_all: pd.DataFrame,
    out_dir: str | Path,
    show: bool = True,
) -> pd.DataFrame:
    """Save Russian comparison charts for the walk-forward experiment."""
    import matplotlib.pyplot as plt

    out_path = Path(out_dir)
    out_path.mkdir(parents=True, exist_ok=True)

    fig, ax = plt.subplots(figsize=(10, 4))
    for model_name, group in equity_curve_all.groupby("model"):
        ax.plot(pd.to_datetime(group["date"]), group["equity"], marker="o", linewidth=2, label=model_name)
    ax.set_title("\u041a\u0440\u0438\u0432\u0430\u044f \u043a\u0430\u043f\u0438\u0442\u0430\u043b\u0430 \u043f\u043e \u043c\u043e\u0434\u0435\u043b\u044f\u043c")
    ax.set_xlabel("\u0414\u0430\u0442\u0430")
    ax.set_ylabel("\u041a\u0430\u043f\u0438\u0442\u0430\u043b, \u0441\u0442\u0430\u0440\u0442 = 1.0")
    ax.grid(True, alpha=0.3)
    ax.legend(title="\u041c\u043e\u0434\u0435\u043b\u044c")
    plt.tight_layout()
    plt.savefig(out_path / "compare_equity_curve.png", dpi=150)
    if show:
        plt.show()
    else:
        plt.close(fig)

    fig, ax = plt.subplots(figsize=(10, 4))
    plot_df = results_all.copy()
    plot_df["label"] = plot_df["model"] + "\n" + plot_df["test_start"].astype(str)
    ax.bar(plot_df["label"], plot_df["realized_return_test"])
    ax.axhline(0, color="black", linewidth=1)
    ax.set_title("\u0414\u043e\u0445\u043e\u0434\u043d\u043e\u0441\u0442\u044c \u0442\u0435\u0441\u0442\u043e\u0432\u043e\u0433\u043e \u043c\u0435\u0441\u044f\u0446\u0430 \u043f\u043e \u043c\u043e\u0434\u0435\u043b\u044f\u043c")
    ax.set_xlabel("\u041c\u043e\u0434\u0435\u043b\u044c")
    ax.set_ylabel("\u0414\u043e\u0445\u043e\u0434\u043d\u043e\u0441\u0442\u044c")
    ax.grid(True, axis="y", alpha=0.3)
    plt.xticks(rotation=20, ha="right")
    plt.tight_layout()
    plt.savefig(out_path / "compare_test_return.png", dpi=150)
    if show:
        plt.show()
    else:
        plt.close(fig)

    if not epoch_scores_all.empty:
        epoch_scores_all = epoch_scores_all.sort_values(["model", "step", "iteration"]).reset_index(drop=True)
        epoch_scores_all.to_csv(out_path / "compare_train_score_by_epoch.csv", index=False)
        plot_epoch = epoch_scores_all[epoch_scores_all["iteration"] >= 0].copy()

        fig, ax = plt.subplots(figsize=(10, 4))
        for model_name, group in plot_epoch.dropna(subset=["mean_score"]).groupby("model"):
            group = group.sort_values("iteration")
            ax.plot(group["iteration"], group["mean_score"], marker="o", linewidth=2, label=model_name)
        ax.set_title("Mean train score \u043f\u043e \u044d\u043f\u043e\u0445\u0430\u043c")
        ax.set_xlabel("\u042d\u043f\u043e\u0445\u0430")
        ax.set_ylabel("\u0421\u0440\u0435\u0434\u043d\u0438\u0439 train score")
        ax.grid(True, alpha=0.3)
        ax.legend(title="\u041c\u043e\u0434\u0435\u043b\u044c")
        plt.tight_layout()
        plt.savefig(out_path / "compare_mean_train_score_by_epoch.png", dpi=150)
        if show:
            plt.show()
        else:
            plt.close(fig)

        fig, ax = plt.subplots(figsize=(10, 4))
        for model_name, group in plot_epoch.dropna(subset=["best_score"]).groupby("model"):
            group = group.sort_values("iteration")
            ax.plot(group["iteration"], group["best_score"], marker="o", linewidth=2, label=model_name)
        ax.set_title("Best train score \u043f\u043e \u044d\u043f\u043e\u0445\u0430\u043c")
        ax.set_xlabel("\u042d\u043f\u043e\u0445\u0430")
        ax.set_ylabel("\u041b\u0443\u0447\u0448\u0438\u0439 train score")
        ax.grid(True, alpha=0.3)
        ax.legend(title="\u041c\u043e\u0434\u0435\u043b\u044c")
        plt.tight_layout()
        plt.savefig(out_path / "compare_best_train_score_by_epoch.png", dpi=150)
        if show:
            plt.show()
        else:
            plt.close(fig)

    fig, ax = plt.subplots(figsize=(10, 4))
    for model_name, group in equity_curve_all.groupby("model"):
        ax.plot(pd.to_datetime(group["date"]), group["drawdown"], marker="o", linewidth=2, label=model_name)
    ax.set_title("\u041f\u0440\u043e\u0441\u0430\u0434\u043a\u0430 \u043f\u043e \u043c\u043e\u0434\u0435\u043b\u044f\u043c")
    ax.set_xlabel("\u0414\u0430\u0442\u0430")
    ax.set_ylabel("\u041f\u0440\u043e\u0441\u0430\u0434\u043a\u0430")
    ax.grid(True, alpha=0.3)
    ax.legend(title="\u041c\u043e\u0434\u0435\u043b\u044c")
    plt.tight_layout()
    plt.savefig(out_path / "compare_drawdown.png", dpi=150)
    if show:
        plt.show()
    else:
        plt.close(fig)

    asset_rows: list[dict[str, str]] = []
    for _, row in results_all.iterrows():
        for asset in json.loads(row["weights_json"]):
            asset_rows.append({"model": row["model"], "asset": asset})
    asset_frequency = (
        pd.DataFrame(asset_rows)
        .groupby(["model", "asset"], as_index=False)
        .size()
        .rename(columns={"size": "selected_count"})
    )
    asset_frequency.to_csv(out_path / "compare_asset_frequency.csv", index=False)

    asset_top = asset_frequency.sort_values("selected_count", ascending=False).head(20).copy()
    asset_top["label"] = asset_top["asset"] + " - " + asset_top["model"]
    fig, ax = plt.subplots(figsize=(10, 6))
    ax.barh(asset_top["label"][::-1], asset_top["selected_count"][::-1])
    ax.set_title("\u0427\u0430\u0441\u0442\u043e\u0442\u0430 \u0432\u044b\u0431\u043e\u0440\u0430 \u0430\u043a\u0442\u0438\u0432\u043e\u0432 \u043f\u043e \u043c\u043e\u0434\u0435\u043b\u044f\u043c")
    ax.set_xlabel("\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e \u0432\u044b\u0431\u043e\u0440\u043e\u0432")
    ax.set_ylabel("\u0410\u043a\u0442\u0438\u0432")
    ax.grid(True, axis="x", alpha=0.3)
    plt.tight_layout()
    plt.savefig(out_path / "compare_asset_frequency.png", dpi=150)
    if show:
        plt.show()
    else:
        plt.close(fig)

    return asset_frequency

def weight_signature(weights: dict[str, float]) -> tuple[tuple[str, float], ...]:
    positive = {asset: float(weight) for asset, weight in weights.items() if float(weight) > 0}
    total = sum(positive.values())
    if total <= 0:
        return tuple()
    normalized = {asset: weight / total for asset, weight in positive.items()}
    return tuple(sorted((asset, round(weight, 4)) for asset, weight in normalized.items()))


def format_weights_compact(weights: dict[str, float]) -> str:
    return ", ".join(f"{asset}:{weight:.2f}" for asset, weight in sorted(weights.items()))


def build_prompt(
    available_assets: list[str],
    previous: list[dict],
    n_candidates: int,
    min_assets: int,
    max_assets: int,
    max_sigma_ann: float,
    iteration: int,
    language: str = "en",
    retry: int = 0,
) -> str:
    ranked = sorted(previous, key=lambda row: row["score"], reverse=True)
    top_best = ranked[:10]
    top_worst = ranked[-5:][::-1] if ranked else []
    compact_best = []
    for row in top_best:
        metrics = row.get("metrics", {})
        compact_best.append(
            {
                "score": round(float(row.get("score", 0.0)), 6),
                "mu_ann": round(float(metrics.get("mu_ann", 0.0)), 6),
                "sigma_q_0.9": round(float(metrics.get("sigma_q_0.9", 0.0)), 6),
                "risk_violation": round(float(metrics.get("risk_violation", 0.0)), 6),
                "concentration": round(float(metrics.get("concentration", 0.0)), 6),
                "weights": row.get("weights", {}),
            }
        )
    compact_worst = []
    for row in top_worst:
        metrics = row.get("metrics", {})
        compact_worst.append(
            {
                "score": round(float(row.get("score", 0.0)), 6),
                "sigma_q_0.9": round(float(metrics.get("sigma_q_0.9", 0.0)), 6),
                "risk_violation": round(float(metrics.get("risk_violation", 0.0)), 6),
                "weights": row.get("weights", {}),
            }
        )

    asset_frequency: dict[str, int] = {}
    asset_weight_sum: dict[str, float] = {}
    for row in top_best:
        for asset, weight in row.get("weights", {}).items():
            asset_frequency[asset] = asset_frequency.get(asset, 0) + 1
            asset_weight_sum[asset] = asset_weight_sum.get(asset, 0.0) + float(weight)
    top_assets = [
        {"asset": asset, "count": count, "avg_weight": round(asset_weight_sum[asset] / count, 4)}
        for asset, count in sorted(asset_frequency.items(), key=lambda item: (-item[1], item[0]))[:15]
    ]

    available_assets_json = json.dumps(available_assets, ensure_ascii=False, separators=(",", ":"))
    best_so_far_json = json.dumps(compact_best[0] if compact_best else None, ensure_ascii=False, separators=(",", ":"))
    top_best_json = json.dumps(compact_best, ensure_ascii=False, separators=(",", ":"))
    top_worst_json = json.dumps(compact_worst, ensure_ascii=False, separators=(",", ":"))
    top_assets_json = json.dumps(top_assets, ensure_ascii=False, separators=(",", ":"))

    if language.lower().startswith("ru"):
        retry_section = ""
        if retry:
            retry_section = """
## Повторная попытка
Предыдущий ответ дал слишком мало валидных или уникальных кандидатов. Верни новые портфели, не копируй уже лучшие варианты.
Частые причины отклонения: тикера нет в списке, слишком мало/много активов, веса не числа, сумма весов далека от 1, дубликаты.
"""

        return f"""# Задача
Выбери {n_candidates} новых long-only портфелей для walk-forward проверки. Используй только обучающее окно и историю уже оцененных портфелей.

# Цель
Максимизировать score, но не нарушать лимит риска.
score = mu_ann - 20 * max(0, sigma_q_0.9 - max_sigma_ann) - 0.02 * concentration

# Параметры
- max_sigma_ann: {max_sigma_ann}
- risk_metric: sigma_q_0.9
- min_assets: {min_assets}
- max_assets: {max_assets}
- iteration: {iteration}
- concentration: sum(weight ** 2)

# Как генерировать кандидатов
- Возьми лучшие портфели как ориентир, но не копируй их дословно.
- Сделай кандидатов различными: один агрессивнее по ожидаемой доходности, один более сбалансированный, один более защитный/диверсифицированный.
- Увеличивай веса активов, которые часто встречаются в лучших портфелях, только если риск остается ниже лимита.
- Избегай комбинаций, похожих на худшие портфели или портфели с risk_violation > 0.
- Обычно держи 3-8 активов; не ставь вес одного актива выше 0.40 без сильной причины.
- Веса должны быть десятичными числами и суммироваться ровно или почти ровно в 1.0.

# Жесткий формат
- Используй только тикеры из available_assets, копируй символы точно.
- Верни ровно {n_candidates} объектов в candidates.
- Каждый объект должен иметь вид {{"weights":{{"TICKER":0.1}}}}.
- Никакого текста вокруг JSON.

# available_assets
{available_assets_json}

# current_best
{best_so_far_json}

# assets_seen_in_best
{top_assets_json}

# top_best_portfolios
{top_best_json}

# worst_portfolios_to_avoid
{top_worst_json}

# Ответ, только JSON
{{"candidates":[{{"weights":{{"SBER":0.30,"GAZP":0.25,"LKOH":0.20,"MOEX":0.25}}}}]}}
{retry_section}"""

    retry_section = ""
    if retry:
        retry_section = """
## Retry
The previous response produced too few valid or unique candidates. Return new portfolios and do not copy the current best.
Common rejection reasons: unknown ticker, too few/many assets, non-numeric weights, weights far from 1.0, duplicates.
"""

    return f"""# Task
Choose {n_candidates} new long-only portfolios for walk-forward testing. Use only the training-window evidence and the scored portfolio history.

# Objective
Maximize score without breaching the risk limit.
score = mu_ann - 20 * max(0, sigma_q_0.9 - max_sigma_ann) - 0.02 * concentration

# Parameters
- max_sigma_ann: {max_sigma_ann}
- risk_metric: sigma_q_0.9
- min_assets: {min_assets}
- max_assets: {max_assets}
- iteration: {iteration}
- concentration: sum(weight ** 2)

# Candidate strategy
- Use the best portfolios as evidence, but do not copy them exactly.
- Make candidates meaningfully different: one return-seeking, one balanced, one more diversified/defensive.
- Increase weights of assets that repeatedly appear in top portfolios only if risk should remain below the limit.
- Avoid combinations similar to the worst portfolios or portfolios with risk_violation > 0.
- Usually use 3-8 assets; avoid any single weight above 0.40 unless strongly justified by prior scores.
- Weights must be decimal numbers and should sum exactly or very close to 1.0.

# Hard output contract
- Use only tickers from available_assets, copied exactly.
- Return exactly {n_candidates} objects in candidates.
- Each object must be shaped as {{"weights":{{"TICKER":0.1}}}}.
- Return raw JSON only.

# available_assets
{available_assets_json}

# current_best
{best_so_far_json}

# assets_seen_in_best
{top_assets_json}

# top_best_portfolios
{top_best_json}

# worst_portfolios_to_avoid
{top_worst_json}

# Output JSON only
{{"candidates":[{{"weights":{{"SBER":0.30,"GAZP":0.25,"LKOH":0.20,"MOEX":0.25}}}}]}}
{retry_section}"""

def coerce_candidate_weights(value: Any) -> dict[str, float] | None:
    if isinstance(value, PortfolioCandidate):
        return value.weights
    if not isinstance(value, dict):
        return None

    for key in ("weights", "portfolio", "allocation", "allocations", "assets", "holdings"):
        nested = value.get(key)
        if isinstance(nested, dict):
            return nested

    weighted_rows = []
    for key in ("weights", "portfolio", "allocation", "allocations", "assets", "holdings"):
        nested = value.get(key)
        if isinstance(nested, list):
            weighted_rows = nested
            break
    if weighted_rows:
        parsed_rows: dict[str, float] = {}
        for row in weighted_rows:
            if not isinstance(row, dict):
                continue
            asset = row.get("asset", row.get("ticker", row.get("symbol", row.get("name"))))
            weight = row.get("weight", row.get("value", row.get("allocation")))
            if asset is not None and weight is not None:
                parsed_rows[str(asset)] = weight
        if parsed_rows:
            return parsed_rows

    ignored_metadata = {"name", "reason", "rationale", "score", "metrics", "comment"}
    numeric_like: dict[str, Any] = {}
    for key, maybe_weight in value.items():
        if key in ignored_metadata:
            continue
        try:
            float(str(maybe_weight).strip().replace("%", ""))
        except (TypeError, ValueError):
            continue
        numeric_like[str(key)] = maybe_weight
    return numeric_like or None


def normalize_candidate_batch_payload(payload: Any) -> Any:
    if isinstance(payload, PortfolioCandidateBatch):
        return payload
    if payload is None:
        return None

    if isinstance(payload, list):
        candidates = payload
    elif isinstance(payload, dict):
        candidates = payload.get("candidates")
        if candidates is None:
            for alternative_key in ("portfolios", "portfolio_candidates", "solutions"):
                if isinstance(payload.get(alternative_key), list):
                    candidates = payload[alternative_key]
                    break
        if candidates is None:
            weights = coerce_candidate_weights(payload)
            candidates = [{"weights": weights}] if weights else None
    else:
        return payload

    if isinstance(candidates, dict):
        weights = coerce_candidate_weights(candidates)
        candidates = [{"weights": weights}] if weights else None
    if not isinstance(candidates, list):
        return {"candidates": candidates}

    normalized_candidates = []
    for candidate in candidates:
        weights = coerce_candidate_weights(candidate)
        normalized_candidates.append({"weights": weights} if weights is not None else candidate)
    return {"candidates": normalized_candidates}


def candidate_batch_validation_message(payload: Any) -> str:
    try:
        PortfolioCandidateBatch.model_validate(payload)
    except ValidationError as exc:
        return "; ".join(f"{'.'.join(str(part) for part in err['loc'])}: {err['msg']}" for err in exc.errors()[:3])
    return ""


def parse_candidate_batch(payload: Any) -> PortfolioCandidateBatch | None:
    if payload is None:
        return None
    payload = normalize_candidate_batch_payload(payload)
    try:
        return PortfolioCandidateBatch.model_validate(payload)
    except ValidationError:
        return None


def parse_weighted_candidates(
    payload: Any,
    available_assets: list[str],
    min_assets: int,
    max_assets: int,
) -> list[dict[str, float]]:
    batch = parse_candidate_batch(payload)
    if batch is None:
        return []

    allowed = set(available_assets)
    out = []
    for candidate in batch.candidates:
        weights = candidate.weights
        clean = {}
        for asset, weight in weights.items():
            asset = str(asset)
            if asset not in allowed:
                continue
            value = float(weight)
            if value > 0:
                clean[asset] = value
        if min_assets <= len(clean) <= max_assets:
            out.append(clean)
    return out


def is_gigachat_model(model: str | None) -> bool:
    if not model:
        return False
    return model.lower().startswith("gigachat")


def normalize_gigachat_model_name(model: str | None) -> str:
    if not model:
        return os.getenv("GIGACHAT_MODEL", "GigaChat-2-Max")
    if model.lower().startswith("gigachat:"):
        return model.split(":", 1)[1]
    if model.lower().startswith("gigachat/"):
        return model.split("/", 1)[1]
    return model


def build_model() -> Any:
    credentials = os.getenv("GIGACHAT_CREDENTIALS")
    access_token = os.getenv("GIGACHAT_ACCESS_TOKEN")
    credentials = credentials.strip() if credentials else None
    access_token = access_token.strip() if access_token else None
    if not credentials and not access_token:
        raise RuntimeError("Set GIGACHAT_CREDENTIALS or GIGACHAT_ACCESS_TOKEN in environment.")

    from langchain_gigachat.chat_models import GigaChat  # type: ignore

    kwargs: dict[str, Any] = {
        "model": os.getenv("GIGACHAT_MODEL", "GigaChat-2-Max"),
        "timeout": float(os.getenv("GIGACHAT_TIMEOUT", "60")),
        "verify_ssl_certs": False,
    }
    if credentials:
        kwargs["credentials"] = credentials
    elif access_token:
        kwargs["access_token"] = access_token
    return GigaChat(**kwargs)


def parse_json_payload_from_text(text: str) -> Any | None:
    cleaned = text.strip()
    fenced = re.search(r"```(?:json)?\s*(.*?)\s*```", cleaned, flags=re.DOTALL | re.IGNORECASE)
    if fenced:
        cleaned = fenced.group(1).strip()

    for candidate in (cleaned,):
        try:
            payload = json.loads(candidate)
            return payload if isinstance(payload, (dict, list)) else None
        except json.JSONDecodeError:
            pass

    starts = [(pos, char) for char in ("{", "[") if (pos := cleaned.find(char)) >= 0]
    if not starts:
        return None
    start, opener = min(starts)
    closer = "}" if opener == "{" else "]"

    if start < 0:
        return None

    depth = 0
    in_string = False
    escape = False
    for pos in range(start, len(cleaned)):
        char = cleaned[pos]
        if in_string:
            if escape:
                escape = False
            elif char == "\\":
                escape = True
            elif char == '"':
                in_string = False
            continue
        if char == '"':
            in_string = True
        elif char == opener:
            depth += 1
        elif char == closer:
            depth -= 1
            if depth == 0:
                try:
                    payload = json.loads(cleaned[start : pos + 1])
                    return payload if isinstance(payload, (dict, list)) else None
                except json.JSONDecodeError:
                    return None
    return None


def build_gigachat_model(model: str | None = None) -> Any:
    if model:
        os.environ["GIGACHAT_MODEL"] = normalize_gigachat_model_name(model)
    return build_model()


def invoke_json_chain(llm: Any, prompt: str, system_prompt: str = SYSTEM_PROMPT) -> PortfolioCandidateBatch | None:
    global LAST_LLM_DEBUG
    LAST_LLM_DEBUG = {
        "stage": "start",
        "error_type": "",
        "error_message": "",
        "raw_text_preview": "",
        "json_found": False,
    }
    try:
        from langchain_core.output_parsers import StrOutputParser  # type: ignore
        from langchain_core.prompts import ChatPromptTemplate  # type: ignore
    except ImportError as exc:
        LAST_LLM_DEBUG.update(
            {
                "stage": "import_langchain_core",
                "error_type": type(exc).__name__,
                "error_message": str(exc),
            }
        )
        return None
    try:
        prompt_template = ChatPromptTemplate.from_messages([("system", system_prompt), ("human", "{task_json}")])
        chain = prompt_template | llm | StrOutputParser()
        text = chain.invoke({"task_json": prompt})
        parsed_json = parse_json_payload_from_text(text)
        LAST_LLM_DEBUG.update(
            {
                "stage": "parse_response",
                "raw_text_preview": text[:1000],
                "json_found": parsed_json is not None,
            }
        )
        batch = parse_candidate_batch(parsed_json)
        if batch is None:
            LAST_LLM_DEBUG.update(
                {
                    "stage": "validate_response",
                    "error_type": "InvalidCandidateBatch",
                    "error_message": candidate_batch_validation_message(normalize_candidate_batch_payload(parsed_json))
                    or "Response JSON did not match PortfolioCandidateBatch",
                }
            )
        return batch
    except Exception as exc:
        LAST_LLM_DEBUG.update(
            {
                "stage": "invoke_model",
                "error_type": type(exc).__name__,
                "error_message": str(exc),
            }
        )
        return None


def call_langchain(prompt: str, model: str, base_url: str | None, temperature: float) -> PortfolioCandidateBatch | None:
    global LAST_LLM_DEBUG
    if is_gigachat_model(model):
        try:
            return invoke_json_chain(build_gigachat_model(model), prompt, system_prompt=SYSTEM_PROMPT_RU)
        except Exception as exc:
            LAST_LLM_DEBUG = {
                "stage": "build_gigachat_model",
                "error_type": type(exc).__name__,
                "error_message": str(exc),
                "raw_text_preview": "",
                "json_found": False,
            }
            return None

    if not os.getenv("OPENAI_API_KEY"):
        LAST_LLM_DEBUG = {
            "stage": "missing_openai_api_key",
            "error_type": "MissingOpenAIAPIKey",
            "error_message": "OPENAI_API_KEY is not set",
            "raw_text_preview": "",
            "json_found": False,
        }
        return None
    try:
        from langchain_openai import ChatOpenAI  # type: ignore
    except ImportError as exc:
        LAST_LLM_DEBUG = {
            "stage": "import_langchain_openai",
            "error_type": type(exc).__name__,
            "error_message": str(exc),
            "raw_text_preview": "",
            "json_found": False,
        }
        return None
    try:
        llm = ChatOpenAI(
            model=model,
            temperature=temperature,
            base_url=base_url,
            timeout=float(os.getenv("OPENAI_TIMEOUT", "60")),
        )
        return invoke_json_chain(llm, prompt)
    except Exception as exc:
        LAST_LLM_DEBUG = {
            "stage": "build_openai_model",
            "error_type": type(exc).__name__,
            "error_message": str(exc),
            "raw_text_preview": "",
            "json_found": False,
        }
        return None


def optimize_return_under_risk(
    prices: pd.DataFrame,
    min_assets: int = 3,
    max_assets: int = 10,
    max_sigma_ann: float = 0.35,
    rolling_window: int = DEFAULT_ROLLING_WINDOW,
    trading_days: int = DEFAULT_TRADING_DAYS,
    initial_random_samples: int = 10,
    iterations: int = 15,
    candidates_per_iter: int = 5,
    seed: int = 42,
    model: str | None = None,
    base_url: str | None = None,
    temperature: float = 1.0,
    prompt_out: str | Path | None = None,
    verbose: bool = False,
    llm_attempts_per_iteration: int = 2,
    progress: bool = False,
) -> tuple[WeightedPortfolioEvaluation, pd.DataFrame]:
    rng = np.random.default_rng(seed)
    model = model or os.getenv("OPENAI_MODEL", DEFAULT_LLM_MODEL)
    base_url = base_url or os.getenv("OPENAI_BASE_URL", DEFAULT_LLM_BASE_URL)
    context = build_rolling_return_risk_context(prices, window=rolling_window, trading_days=trading_days)
    available_assets = context.tickers

    rows = []
    epoch_rows = []
    previous: list[dict] = []
    seen: set[tuple[tuple[str, float], ...]] = set()
    best: WeightedPortfolioEvaluation | None = None

    def evaluate_and_store(iteration: int, source: str, weights: dict[str, float]) -> bool:
        nonlocal best
        key = weight_signature(weights)
        if key in seen:
            return False
        seen.add(key)
        ev = evaluate_weighted_portfolio(weights, context, max_sigma_ann, min_assets, max_assets)
        row = {
            "iteration": iteration,
            "source": source,
            "score": ev.score,
            "weights": json.dumps(ev.weights, ensure_ascii=False),
        }
        row.update(ev.metrics)
        rows.append(row)
        previous.append({"weights": ev.weights, "score": ev.score, "metrics": ev.metrics})
        if best is None or ev.score > best.score:
            best = ev
        if verbose:
            best_score = best.score if best is not None else float("nan")
            print(
                f"iter={iteration:>2} source={source:<4} "
                f"score={ev.score:.4f} best={best_score:.4f} "
                f"mu={ev.metrics.get('mu_ann', float('nan')):.4f} "
                f"sigma_q0.9={ev.metrics.get('sigma_q_0.9', float('nan')):.4f} "
                f"risk_violation={ev.metrics.get('risk_violation', float('nan')):.4f} "
                f"n_assets={ev.metrics.get('n_assets', 0)} "
                f"weights={format_weights_compact(ev.weights)}",
                flush=True,
            )
        return True

    for _ in range(initial_random_samples):
        evaluate_and_store(-1, "seed", random_weighted_portfolio(rng, available_assets, min_assets, max_assets))

    for iteration in range(iterations):
        prompt_language = "ru" if is_gigachat_model(model) else "en"
        evaluated_this_iter = 0
        best_before_iter = best.score if best is not None else float("nan")
        if progress:
            print(f"iter={iteration + 1}/{iterations} requesting candidates...", flush=True)
        for llm_attempt in range(max(1, llm_attempts_per_iteration)):
            prompt = build_prompt(
                available_assets,
                previous,
                candidates_per_iter - evaluated_this_iter,
                min_assets,
                max_assets,
                max_sigma_ann,
                iteration,
                language=prompt_language,
                retry=llm_attempt,
            )
            if prompt_out:
                Path(prompt_out).parent.mkdir(parents=True, exist_ok=True)
                Path(prompt_out).write_text(prompt, encoding="utf-8")
            payload = call_langchain(prompt, model, base_url, temperature)
            llm_debug = dict(LAST_LLM_DEBUG)
            parsed_batch = parse_candidate_batch(payload) if payload else None
            raw_candidates_count = len(parsed_batch.candidates) if parsed_batch else 0
            candidates = parse_weighted_candidates(parsed_batch, available_assets, min_assets, max_assets) if parsed_batch else []
            source = "llm" if llm_attempt == 0 else "llm_retry"
            accepted_this_attempt = 0
            for weights in candidates:
                if evaluated_this_iter >= candidates_per_iter:
                    break
                if evaluate_and_store(iteration, source, weights):
                    evaluated_this_iter += 1
                    accepted_this_attempt += 1
            best_score = best.score if best is not None else float("nan")
            epoch_rows.append(
                {
                    "iteration": iteration,
                    "attempt": llm_attempt + 1,
                    "source": source,
                    "requested_candidates": candidates_per_iter,
                    "raw_candidates": raw_candidates_count,
                    "parsed_candidates": len(candidates),
                    "accepted_candidates": accepted_this_attempt,
                    "accepted_total_iteration": evaluated_this_iter,
                    "llm_error_stage": llm_debug.get("stage", ""),
                    "llm_error_type": llm_debug.get("error_type", ""),
                    "llm_error_message": llm_debug.get("error_message", ""),
                    "llm_json_found": llm_debug.get("json_found", False),
                    "llm_raw_preview": llm_debug.get("raw_text_preview", ""),
                    "best_score_before": best_before_iter,
                    "best_score_after": best_score,
                    "improved": bool(best_score > best_before_iter) if not np.isnan(best_before_iter) else bool(accepted_this_attempt),
                }
            )
            if evaluated_this_iter >= candidates_per_iter:
                break
            if verbose:
                print(
                    f"iter={iteration:>2} source=retry "
                    f"valid={evaluated_this_iter}/{candidates_per_iter} "
                    f"raw={raw_candidates_count} parsed={len(candidates)} "
                    f"stage={llm_debug.get('stage', '')} "
                    f"err={llm_debug.get('error_type', '')} "
                    f"attempt={llm_attempt + 1}/{max(1, llm_attempts_per_iteration)}"
                )
        if progress:
            best_score = best.score if best is not None else float("nan")
            print(
                f"iter={iteration + 1}/{iterations} accepted={evaluated_this_iter}/{candidates_per_iter} "
                f"best={best_score:.4f}",
                flush=True,
            )

    if best is None:
        raise ValueError("No weighted portfolios were evaluated")
    history = pd.DataFrame(rows)
    if epoch_rows:
        history.attrs["epoch_log"] = pd.DataFrame(epoch_rows)
    return best, history


